manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/t0bybr
      #url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-pim447
      import: app/west.yml
  self:
    path: config
